jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Testsigma script
        env:
          TESTSIGMA_API_KEY: ${{ secrets.TESTSIGMA_API_KEY }}
        run: |
          bash scripts/testsigma.sh

      - name: Upload Testsigma PDF Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: testsigma-execution-report
          path: testsigma_execution_report.pdf
