name: Testsigma Execution

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Testsigma script
        run: bash scripts/testsigma.sh
        env:
          TESTSIGMA_API_KEY: ${{ secrets.TESTSIGMA_API_KEY }}

      - name: Upload Testsigma PDF Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: testsigma-execution-report
          path: Reports/testsigma_execution_report.pdf
          if-no-files-found: warn
